### ISSUE TITLE
Fontconfig error: Cannot load default config file

### ISSUE THREAD

**Issue by Namsnugax** [rednoah/java-installer#37]
Hello,
I have a java program running on my synology DS218 but there is a problem with Fontconfig.
Here is the error I get:

Fontconfig error: Cannot load default config file
java.lang.NullPointerException: Cannot load from short array because "sun.awt.FontConfiguration.head" is null
	at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1262)
	at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:224)
	at java.desktop/sun.awt.FontConfiguration.init(FontConfiguration.java:106)
	at java.desktop/sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:706)
	at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:352)
	at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:309)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/sun.font.SunFontManager.&lt;init&gt;(SunFontManager.java:309)
	at java.desktop/sun.awt.FcFontManager.&lt;init&gt;(FcFontManager.java:35)
	at java.desktop/sun.awt.X11FontManager.&lt;init&gt;(X11FontManager.java:56)
	at java.desktop/sun.font.PlatformFontInfo.createFontManager(PlatformFontInfo.java:37)
	at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:51)
	at java.desktop/java.awt.Font.&lt;init&gt;(Font.java:642)
	at java.desktop/java.awt.Font.createFont(Font.java:1250)

Code to reproduce the error :

public static void main(final String[] args) throws LoginException {
		try {
			final GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
			for (final String string : ge.getAvailableFontFamilyNames()) {
				System.out.println(string);
			}
		} catch (final Exception e) {
			e.printStackTrace();
		}
	}

**Comment by rednoah** [comment]
`DS218` is `headless`. The error message indicates issues with running a Desktop application which unsurprisingly doesn't work on a `headless` machine.

Can you elaborate? What exactly are you doing? What exactly are you trying to do?

**Comment by Namsnugax** [comment]
To summarize, I use the JFreechart library to display a graph and writing text in the title or the axes triggers this error. The code works perfectly on my computer but returns this error on the NAS. This problem also happens when I want to add text on an image with the method "java.awt.Graphics2D.drawString(String str, int x, int y)". I haven't found a way to do otherwise.

**Comment by rednoah** [comment]
So you have a Java AWT / Swing Desktop application? A GUI application running on a Linux Desktop GUI?

**Comment by Namsnugax** [comment]
I have a jar executable archive, maybe I need to configure it in a certain way for linux? I'm used to work on windows and I thought java was cross platform. There is no graphical interface in my application, it's a bot discord but when I want to create an image with text with the java library "java.awt" it doesn't find a font (if I understood the error correctly).

**Comment by rednoah** [comment]
`java.awt.*` requires a complete Linux Desktop environment and X11 dependencies. You probably won't be able to make that work on a Synology NAS. You'll probably want to run a normal Desktop Linux environment in a `docker` container.

**Comment by Namsnugax** [comment]
Ok I understand better! Unfortunately I think that the docker conatener is not compatible with my DS218 NAS :( 
https://www.synology.com/fr-fr/dsm/packages/Docker
